# Generated by Django 5.0.4 on 2024-04-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contaduriia',
            fields=[
                ('id_contaduria', models.AutoField(primary_key=True, serialize=False)),
                ('numero_escritura', models.IntegerField(max_length=50)),
                ('valor_beneficiencia', models.IntegerField(max_length=50)),
                ('valor_registro', models.IntegerField(max_length=50)),
                ('valor_deposito', models.IntegerField(max_length=50)),
                ('valor_bono', models.IntegerField(max_length=50)),
                ('nombre_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta.proyecto')),
            ],
            options={
                'verbose_name': 'contaduria',
                'verbose_name_plural': 'contadurias',
                'db_table': 'contaduria',
            },
        ),
    ]
