# Generated by Django 5.0.4 on 2024-04-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_contaduriia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaduriia',
            name='numero_escritura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduriia',
            name='valor_beneficiencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduriia',
            name='valor_bono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduriia',
            name='valor_deposito',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduriia',
            name='valor_registro',
            field=models.IntegerField(),
        ),
    ]
