# Generated by Django 5.0.4 on 2024-04-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0003_alter_contaduriia_numero_escritura_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contaduriia',
            new_name='Contaduria',
        ),
    ]
