# Generated by Django 5.0.4 on 2024-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_rename_contaduriia_contaduria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contaduria',
            old_name='nombre_proyecto',
            new_name='id_nombre_proyecto',
        ),
    ]
