# Generated by Django 5.0.4 on 2024-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_remove_contaduria_id_nombre_proyecto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaduria',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='numero_escritura',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_beneficiencia',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_bono',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_deposito',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_registro',
            field=models.FloatField(),
        ),
    ]
