# Generated by Django 5.0.4 on 2024-04-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0007_contaduria_total_alter_contaduria_numero_escritura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaduria',
            name='numero_escritura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_beneficiencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_bono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_deposito',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contaduria',
            name='valor_registro',
            field=models.IntegerField(),
        ),
    ]
