# Generated by Django 5.0.4 on 2024-04-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0008_alter_contaduria_numero_escritura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuario',
            },
        ),
    ]
