# Generated by Django 5.0.4 on 2024-04-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0009_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaduria',
            name='valor_bono',
        ),
    ]
