# Generated by Django 5.0.4 on 2024-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0011_alter_contaduria_id_contaduria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contaduria_bene',
            fields=[
                ('id_contaduria', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_escritura', models.IntegerField()),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('valor_beneficiencia', models.IntegerField()),
                ('valor_deposito', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'contaduria_bene',
                'verbose_name_plural': 'contadurias_bene',
                'db_table': 'contaduria_bene',
            },
        ),
        migrations.CreateModel(
            name='Contaduria_regi',
            fields=[
                ('id_contaduria', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_escritura', models.IntegerField()),
                ('nombre_proyecto', models.CharField(max_length=50)),
                ('valor_registro', models.IntegerField()),
                ('valor_deposito', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name': 'contaduria_regi',
                'verbose_name_plural': 'contadurias_regi',
                'db_table': 'contaduria_regi',
            },
        ),
        migrations.CreateModel(
            name='Proyecto_bene',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'proyecto_bene',
                'verbose_name_plural': 'proyectos_bene',
                'db_table': 'proyecto_bene',
            },
        ),
        migrations.CreateModel(
            name='Proyecto_regi',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'proyecto_regi',
                'verbose_name_plural': 'proyectos_regi',
                'db_table': 'proyecto_regi',
            },
        ),
    ]
